"""
SyncBoard 全局 Django 配置。

集中定义：
- INSTALLED_APPS（4 个自有 app + DRF + Channels + Haystack + corsheaders）
- DATABASES / CACHES / CHANNEL_LAYERS（均用 Redis）
- CELERY_BROKER（Redis）
- HAYSTACK（Elasticsearch 7）
- CORS / STATIC / MEDIA / ASGI_APPLICATION

修改配置时需要同步检查 backend/celery.py 和 backend/asgi.py 中对应的初始化顺序。

Generated by 'django-admin startproject' using Django 6.0.1.
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 环境变量文件
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'unsafe-default-key')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS: 开发/测试环境默认包含 testserver（Django test client 默认 Host）。
# 生产环境必须列出显式主机名，禁止使用 "*"（DEBUG=False 时 Django 会拒绝 "*"）。
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'rest_framework',
    'room',
    'qa_center',
    'system',
    'bug_tracker',
    'corsheaders',
    'haystack',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 使用 os.environ.get 读取 docker-compose 传入的变量
        'NAME': os.environ.get('DB_NAME', 'syncboard'),
        'USER': os.environ.get('DB_USER', 'Liujia'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/django_static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS 配置
# 注意：当使用 withCredentials 时，不能使用 CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
ASGI_APPLICATION = 'backend.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # 这里的地址取决于你的 Redis 安装，默认是 localhost:6379
            "hosts": [(os.environ.get('REDIS_HOST', '127.0.0.1'), 6379)],
        },
    },
}

# Haystack Settings
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'es_backend.CustomElasticsearch7SearchEngine',
        'URL': os.environ.get('HAYSTACK_URL', 'http://127.0.0.1:9200/'),
        'INDEX_NAME': 'haystack',
    },
}

# Celery Settings
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
HAYSTACK_SIGNAL_PROCESSOR = 'backend.signal_processors.CelerySignalProcessor'

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'backend.utils.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('ANON_THROTTLE_RATE', '100/min'),
        'user': os.environ.get('USER_THROTTLE_RATE', '1000/min'),
        'screenshot': os.environ.get('SCREENSHOT_THROTTLE_RATE', '120/min'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

CSRF_TRUSTED_ORIGINS = ['http://localhost:5173', 'http://127.0.0.1:5173']

# CSRF cookie settings for cross-origin requests from frontend dev server
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Frontend needs to read the cookie to send X-CSRFToken header
SESSION_COOKIE_SAMESITE = 'Lax'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'qa_center.runner': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'qa_center.recorder': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}











# QA Center Feature Flags (production upgrade)
USE_CELERY_TASKS = os.environ.get("USE_CELERY_TASKS", "False").lower() == "true"
USE_REAL_CI = os.environ.get("USE_REAL_CI", "False").lower() == "true"
USE_SEMAPHORE = os.environ.get("USE_SEMAPHORE", "False").lower() == "true"
USE_UNIFIED_API_RUNNER = os.environ.get("USE_UNIFIED_API_RUNNER", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_API_AUTO = os.environ.get("USE_UNIFIED_RUNNER_FOR_API_AUTO", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_API_AUTO_CASE = os.environ.get("USE_UNIFIED_RUNNER_FOR_API_AUTO_CASE", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_API_AUTO_SUITE = os.environ.get("USE_UNIFIED_RUNNER_FOR_API_AUTO_SUITE", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_RUNPLAN = os.environ.get("USE_UNIFIED_RUNNER_FOR_RUNPLAN", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_RUNPLAN_SERIAL = os.environ.get("USE_UNIFIED_RUNNER_FOR_RUNPLAN_SERIAL", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_RUNPLAN_PARALLEL = os.environ.get("USE_UNIFIED_RUNNER_FOR_RUNPLAN_PARALLEL", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_ASYNC_TRIGGERS = os.environ.get("USE_UNIFIED_RUNNER_FOR_ASYNC_TRIGGERS", "True").lower() == "true"
USE_UNIFIED_RUNNER_FOR_LEGACY = os.environ.get("USE_UNIFIED_RUNNER_FOR_LEGACY", "True").lower() == "true"
PERF_MAX_CONCURRENT = int(os.environ.get("PERF_MAX_CONCURRENT", "5"))
UI_TEST_MAX_CONCURRENT_RUNNERS = int(os.environ.get("UI_TEST_MAX_CONCURRENT_RUNNERS", "2"))
# ── 压力测试 URL 预检配置 ─────────────────────────────────────
PERF_ALLOW_LOCALHOST = os.environ.get("PERF_ALLOW_LOCALHOST", "false").lower() == "true"
PERF_ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("PERF_ALLOWED_HOSTS", "").split(",") if h.strip()
]
PERF_BLOCK_PRIVATE_CIDRS = os.environ.get("PERF_BLOCK_PRIVATE_CIDRS", "true").lower() == "true"
PERF_PROBE_TIMEOUT_SECONDS = float(os.environ.get("PERF_PROBE_TIMEOUT_SECONDS", "5"))
PERF_BLOCKED_SCHEMES = tuple(
    s.strip() for s in os.environ.get(
        "PERF_BLOCKED_SCHEMES",
        "file,ftp,gopher,javascript,data,vbscript",
    ).split(",") if s.strip()
)
PERF_BLOCKED_HOSTS = tuple(
    h.strip() for h in os.environ.get(
        "PERF_BLOCKED_HOSTS",
        "169.254.169.254,metadata.google.internal,metadata,100.100.100.200",
    ).split(",") if h.strip()
)
PERF_BLOCKED_CIDRS = tuple(
    c.strip() for c in os.environ.get(
        "PERF_BLOCKED_CIDRS",
        "169.254.0.0/16,100.64.0.0/10",
    ).split(",") if c.strip()
)
# ── 生产级执行器配置 ─────────────────────────────────────────
PERF_EXTRA_TIMEOUT_SECONDS = int(os.environ.get("PERF_EXTRA_TIMEOUT_SECONDS", "30"))
PERF_GRACEFUL_STOP_TIMEOUT = int(os.environ.get("PERF_GRACEFUL_STOP_TIMEOUT", "5"))
PERF_ARTIFACT_RETENTION_DAYS = int(os.environ.get("PERF_ARTIFACT_RETENTION_DAYS", "7"))
PERF_KEEP_FAILED_ARTIFACTS = os.environ.get("PERF_KEEP_FAILED_ARTIFACTS", "true").lower() == "true"
# API 校验上限
PERF_MAX_USERS_PER_TEST = int(os.environ.get("PERF_MAX_USERS_PER_TEST", "10000"))
PERF_MAX_DURATION_SECONDS = int(os.environ.get("PERF_MAX_DURATION_SECONDS", "3600"))
PERF_MAX_BODY_BYTES = int(os.environ.get("PERF_MAX_BODY_BYTES", str(1024 * 1024)))  # 1MB
PERF_MAX_HEADERS_COUNT = int(os.environ.get("PERF_MAX_HEADERS_COUNT", "50"))
# 项目配额默认值
PERF_PROJECT_MAX_CONCURRENT = int(os.environ.get("PERF_PROJECT_MAX_CONCURRENT", "2"))
PERF_PROJECT_MAX_USERS = int(os.environ.get("PERF_PROJECT_MAX_USERS", "1000"))
PERF_PROJECT_MAX_DURATION = int(os.environ.get("PERF_PROJECT_MAX_DURATION", "600"))
PERF_PROJECT_DAILY_RUNS = int(os.environ.get("PERF_PROJECT_DAILY_RUNS", "50"))
# ── v2 分布式执行器配置 ─────────────────────────────────────
PERF_RUNNER_BACKEND = os.environ.get("PERF_RUNNER_BACKEND", "local")  # local | docker | k8s
PERF_K8S_NAMESPACE = os.environ.get("PERF_K8S_NAMESPACE", "default")
PERF_ARTIFACT_STORAGE = os.environ.get("PERF_ARTIFACT_STORAGE", "local")  # local | s3 | minio
PERF_K8S_DEFAULT_CPU_LIMIT = os.environ.get("PERF_K8S_DEFAULT_CPU_LIMIT", "2")
PERF_K8S_DEFAULT_MEMORY_LIMIT = os.environ.get("PERF_K8S_DEFAULT_MEMORY_LIMIT", "4Gi")
PERF_DOCKER_IMAGE = os.environ.get("PERF_DOCKER_IMAGE", "syncboard/locust-worker:latest")
DEVOPS_WEBHOOK_MAX_BODY_BYTES = int(os.environ.get("DEVOPS_WEBHOOK_MAX_BODY_BYTES", str(256 * 1024)))
