# Generated by Django 6.0.1 on 2026-06-08 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0011_project_api_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='复现步骤')),
                ('expected', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual', models.TextField(blank=True, verbose_name='实际结果')),
                ('environment', models.CharField(blank=True, max_length=100, verbose_name='环境')),
                ('severity', models.CharField(choices=[('blocker', '阻塞'), ('critical', '严重'), ('major', '一般'), ('minor', '次要'), ('trivial', '轻微')], default='major', max_length=20, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('new', '新建'), ('confirmed', '已确认'), ('assigned', '已指派'), ('fixing', '修复中'), ('fixed', '已修复'), ('verifying', '待验证'), ('closed', '已关闭'), ('reopened', '重新打开'), ('rejected', '已拒绝')], default='new', max_length=20, verbose_name='状态')),
                ('source_test_type', models.CharField(choices=[('manual', '手工'), ('api_auto', '接口自动化'), ('performance', '性能测试'), ('ui_auto', 'UI 自动化')], default='manual', max_length=20, verbose_name='来源类型')),
                ('source_case_id', models.IntegerField(blank=True, null=True, verbose_name='来源用例ID')),
                ('source_result_id', models.IntegerField(blank=True, null=True, verbose_name='来源结果ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL, verbose_name='当前负责人')),
                ('fixer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_bugs', to=settings.AUTH_USER_MODEL, verbose_name='修复人')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bugs', to='room.task', verbose_name='关联任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='room.project', verbose_name='所属项目')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bugs', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bug',
                'db_table': 'bug',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bug_tracker.bug', verbose_name='Bug')),
            ],
            options={
                'verbose_name': 'Bug 评论',
                'verbose_name_plural': 'Bug 评论',
                'db_table': 'bug_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='bug_tracker.bug', verbose_name='Bug')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_transitions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'Bug 流转记录',
                'verbose_name_plural': 'Bug 流转记录',
                'db_table': 'bug_transition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['project', 'status'], name='bug_project_eb35c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['assignee', 'status'], name='bug_assigne_a4faed_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['reporter', '-created_at'], name='bug_reporte_0739b6_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['source_test_type', 'source_case_id'], name='bug_source__b40fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='bugcomment',
            index=models.Index(fields=['bug', 'created_at'], name='bug_comment_bug_id_3babd8_idx'),
        ),
        migrations.AddIndex(
            model_name='bugtransition',
            index=models.Index(fields=['bug', '-created_at'], name='bug_transit_bug_id_531f9e_idx'),
        ),
    ]
