# Generated by Django 6.0.1 on 2026-02-08 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='权限标识')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='前端路由路径')),
                ('type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单'), ('button', '按钮')], max_length=20, verbose_name='类型')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单/权限',
                'verbose_name_plural': '菜单/权限管理',
                'db_table': 'system_menu',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='角色标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='system.menu', verbose_name='菜单权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色管理',
                'db_table': 'system_role',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='system.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展资料',
                'verbose_name_plural': '用户扩展资料',
                'db_table': 'system_user_profile',
            },
        ),
    ]
