# Generated by Django 6.0.1 on 2026-02-09 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='SystemUserProfile',
        ),
        migrations.AlterModelOptions(
            name='systemuserprofile',
            options={'verbose_name': '系统用户扩展资料', 'verbose_name_plural': '系统用户扩展资料'},
        ),
    ]
