# Generated by Django 6.0.1 on 2026-02-07 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试用例名称')),
                ('url', models.CharField(max_length=1000, verbose_name='请求地址')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('expected_status', models.IntegerField(blank=True, null=True, verbose_name='期望状态码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API测试用例',
                'verbose_name_plural': 'API测试用例',
                'db_table': 'qa_api_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='响应状态码')),
                ('response_body', models.TextField(blank=True, verbose_name='响应体')),
                ('response_headers', models.JSONField(default=dict, verbose_name='响应头')),
                ('response_time_ms', models.IntegerField(verbose_name='响应时间(ms)')),
                ('passed', models.BooleanField(verbose_name='是否通过')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qa_center.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'API测试结果',
                'verbose_name_plural': 'API测试结果',
                'db_table': 'qa_api_test_results',
                'ordering': ['-executed_at'],
            },
        ),
    ]
