# Generated by Django 6.0.1 on 2026-02-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='assertions',
            field=models.JSONField(blank=True, default=list, verbose_name='断言配置'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='assertion_results',
            field=models.JSONField(blank=True, default=list, verbose_name='断言结果详情'),
        ),
    ]
