# Generated by Django 6.0.1 on 2026-02-08 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0002_apitestcase_assertions_and_more'),
        ('room', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试用例名称')),
                ('url', models.CharField(max_length=1000, verbose_name='起始URL')),
                ('steps', models.JSONField(default=list, verbose_name='测试步骤')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_test_cases', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试用例',
                'verbose_name_plural': 'UI测试用例',
                'db_table': 'qa_ui_test_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
