# Generated by Django 6.0.1 on 2026-02-08 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0003_uitestcase'),
        ('room', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('api', '接口测试'), ('ui', 'UI测试'), ('performance', '性能测试'), ('regression', '回归测试')], max_length=20, verbose_name='测试类型')),
                ('name', models.CharField(max_length=200, verbose_name='测试名称')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误'), ('running', '运行中'), ('pending', '待执行')], default='pending', max_length=20, verbose_name='测试状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行时长(ms)')),
                ('test_params', models.JSONField(blank=True, default=dict, verbose_name='测试参数')),
                ('test_steps', models.JSONField(blank=True, default=list, verbose_name='测试步骤')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('test_log', models.TextField(blank=True, verbose_name='测试日志')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('throughput', models.FloatField(blank=True, null=True, verbose_name='吞吐量(req/s)')),
                ('error_rate', models.FloatField(blank=True, null=True, verbose_name='错误率(%)')),
                ('concurrent_users', models.IntegerField(blank=True, null=True, verbose_name='并发用户数')),
                ('test_environment', models.CharField(blank=True, max_length=200, verbose_name='测试环境')),
                ('browser_info', models.CharField(blank=True, max_length=200, verbose_name='浏览器信息')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='qa_center.apitestcase', verbose_name='关联API用例')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tests', to=settings.AUTH_USER_MODEL, verbose_name='执行人员')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='room.project', verbose_name='所属项目')),
                ('ui_test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='qa_center.uitestcase', verbose_name='关联UI用例')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'db_table': 'qa_test_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='截图名称')),
                ('description', models.TextField(blank=True, verbose_name='截图描述')),
                ('image', models.ImageField(upload_to='test_screenshots/%Y/%m/%d/', verbose_name='截图文件')),
                ('step_index', models.IntegerField(blank=True, null=True, verbose_name='步骤序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='qa_center.testresult', verbose_name='关联测试结果')),
            ],
            options={
                'verbose_name': '测试截图',
                'verbose_name_plural': '测试截图',
                'db_table': 'qa_test_screenshots',
                'ordering': ['step_index', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test_type', 'status'], name='qa_test_res_test_ty_2fa477_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['project', 'created_at'], name='qa_test_res_project_f62f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['executed_by', 'created_at'], name='qa_test_res_execute_f5c965_idx'),
        ),
    ]
