# Generated by Django 6.0.1 on 2026-02-10 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0005_alter_testresult_actual_result_and_more'),
        ('room', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('test_type', models.CharField(choices=[('api', '接口测试'), ('ui', 'UI测试'), ('performance', '性能测试'), ('regression', '回归测试')], max_length=20, verbose_name='测试类型')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('scheduled', '定时触发'), ('webhook', 'Webhook触发')], default='manual', max_length=20, verbose_name='触发方式')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron表达式（定时任务）')),
                ('webhook_url', models.CharField(blank=True, max_length=500, verbose_name='Webhook URL')),
                ('test_config', models.JSONField(blank=True, default=dict, verbose_name='测试配置')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='idle', max_length=20, verbose_name='当前状态')),
                ('execution_count', models.IntegerField(default=0, verbose_name='执行次数')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='成功时通知')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='失败时通知')),
                ('notification_channels', models.JSONField(blank=True, default=list, verbose_name='通知渠道')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('last_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_task', to='qa_center.testresult', verbose_name='最后执行结果')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tasks', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'qa_test_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
