# Generated by Django 6.0.1 on 2026-02-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0006_testtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='source',
            field=models.CharField(choices=[('devops', 'DevOps执行'), ('single', '单个用例执行')], default='single', max_length=20, verbose_name='结果来源'),
        ),
    ]
