# Generated by Django 6.0.1 on 2026-02-10 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0007_testresult_source'),
        ('room', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitestcase',
            name='assertions',
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='content_type',
            field=models.CharField(choices=[('application/json', 'JSON'), ('application/x-www-form-urlencoded', 'Form'), ('multipart/form-data', 'Multipart'), ('text/plain', 'Text'), ('text/xml', 'XML')], default='application/json', max_length=50, verbose_name='Content-Type'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='description',
            field=models.TextField(blank=True, verbose_name='用例描述'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='expected_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='预期响应'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='body',
            field=models.TextField(blank=True, verbose_name='请求体'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='expected_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='预期状态码'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='name',
            field=models.CharField(max_length=200, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='请求URL'),
        ),
        migrations.AlterField(
            model_name='testscreenshot',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='截图名称'),
        ),
        migrations.AlterField(
            model_name='testscreenshot',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='qa_center.testresult', verbose_name='测试结果'),
        ),
        migrations.CreateModel(
            name='PerformanceTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('url', models.CharField(max_length=1000, verbose_name='请求URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('body', models.TextField(blank=True, verbose_name='请求体')),
                ('concurrent_users', models.IntegerField(default=10, verbose_name='并发用户数')),
                ('duration_seconds', models.IntegerField(default=60, verbose_name='测试持续时间(秒)')),
                ('ramp_up_seconds', models.IntegerField(default=10, verbose_name='预热时间(秒)')),
                ('requests_per_second', models.IntegerField(blank=True, null=True, verbose_name='每秒请求数限制')),
                ('expected_response_time_ms', models.IntegerField(default=1000, verbose_name='预期响应时间(ms)')),
                ('expected_throughput', models.FloatField(blank=True, null=True, verbose_name='预期吞吐量(req/s)')),
                ('expected_error_rate', models.FloatField(default=5.0, verbose_name='预期最大错误率(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_test_cases', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '性能测试用例',
                'verbose_name_plural': '性能测试用例',
                'db_table': 'qa_performance_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField(verbose_name='总请求数')),
                ('successful_requests', models.IntegerField(verbose_name='成功请求数')),
                ('failed_requests', models.IntegerField(verbose_name='失败请求数')),
                ('avg_response_time_ms', models.FloatField(verbose_name='平均响应时间(ms)')),
                ('min_response_time_ms', models.FloatField(verbose_name='最小响应时间(ms)')),
                ('max_response_time_ms', models.FloatField(verbose_name='最大响应时间(ms)')),
                ('p50_response_time_ms', models.FloatField(verbose_name='P50响应时间(ms)')),
                ('p90_response_time_ms', models.FloatField(verbose_name='P90响应时间(ms)')),
                ('p95_response_time_ms', models.FloatField(verbose_name='P95响应时间(ms)')),
                ('p99_response_time_ms', models.FloatField(verbose_name='P99响应时间(ms)')),
                ('throughput', models.FloatField(verbose_name='吞吐量(req/s)')),
                ('error_rate', models.FloatField(verbose_name='错误率(%)')),
                ('response_time_distribution', models.JSONField(blank=True, default=dict, verbose_name='响应时间分布')),
                ('throughput_over_time', models.JSONField(blank=True, default=list, verbose_name='吞吐量时间序列')),
                ('response_time_over_time', models.JSONField(blank=True, default=list, verbose_name='响应时间时间序列')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qa_center.performancetestcase', verbose_name='测试用例')),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_details', to='qa_center.testresult', verbose_name='关联测试结果')),
            ],
            options={
                'verbose_name': '性能测试结果',
                'verbose_name_plural': '性能测试结果',
                'db_table': 'qa_performance_test_results',
                'ordering': ['-executed_at'],
            },
        ),
    ]
