# Generated by Django 6.0.1 on 2026-03-31 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0008_remove_apitestcase_assertions_and_more'),
        ('room', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAutoTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('url', models.CharField(max_length=1000, verbose_name='请求URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('content_type', models.CharField(choices=[('application/json', 'JSON'), ('application/x-www-form-urlencoded', 'Form'), ('multipart/form-data', 'Multipart'), ('text/plain', 'Text')], default='application/json', max_length=50, verbose_name='Content-Type')),
                ('body', models.TextField(blank=True, verbose_name='请求体')),
                ('expected_status', models.IntegerField(blank=True, null=True, verbose_name='预期状态码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auto_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'API自动化测试用例',
                'verbose_name_plural': 'API自动化测试用例',
                'db_table': 'qa_api_auto_cases',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiAutoTestAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion_type', models.CharField(choices=[('status_code', '状态码断言'), ('json_equals', 'JSON字段值断言'), ('json_exists', 'JSON字段存在断言'), ('json_contains', 'JSON字段包含断言'), ('response_time', '响应时间断言')], max_length=20, verbose_name='断言类型')),
                ('json_path', models.CharField(blank=True, help_text='例如: data.user.name 或 result[0].id', max_length=500, verbose_name='JSON路径')),
                ('expected_value', models.CharField(blank=True, help_text='期望的值或表达式', max_length=1000, verbose_name='预期值')),
                ('comparison_operator', models.CharField(default='eq', help_text='eq(等于), ne(不等于), gt(大于), gte(大于等于), lt(小于), lte(小于等于), contains(包含)', max_length=10, verbose_name='比较操作符')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='失败时的错误信息')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='qa_center.apiautotestcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': 'API自动化测试断言',
                'verbose_name_plural': 'API自动化测试断言',
                'db_table': 'qa_api_auto_assertions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiAutoTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20, verbose_name='执行状态')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_cases', models.IntegerField(default=0, verbose_name='错误数')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行时长(ms)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_auto_tests', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
            ],
            options={
                'verbose_name': 'API自动化测试结果',
                'verbose_name_plural': 'API自动化测试结果',
                'db_table': 'qa_api_auto_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiAutoTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='响应状态码')),
                ('response_body', models.TextField(blank=True, verbose_name='响应体')),
                ('response_headers', models.JSONField(default=dict, verbose_name='响应头')),
                ('response_time_ms', models.IntegerField(verbose_name='响应时间(ms)')),
                ('passed', models.BooleanField(verbose_name='是否通过')),
                ('assertion_details', models.JSONField(default=list, verbose_name='断言详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='qa_center.apiautotestcase', verbose_name='测试用例')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='qa_center.apiautotestresult', verbose_name='测试结果')),
            ],
            options={
                'verbose_name': 'API自动化用例执行结果',
                'verbose_name_plural': 'API自动化用例执行结果',
                'db_table': 'qa_api_auto_case_results',
                'ordering': ['executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiAutoTestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, verbose_name='套件描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auto_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_auto_suites', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API自动化测试套件',
                'verbose_name_plural': 'API自动化测试套件',
                'db_table': 'qa_api_auto_suites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='apiautotestresult',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='qa_center.apiautotestsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='apiautotestcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='qa_center.apiautotestsuite', verbose_name='所属套件'),
        ),
    ]
