# Generated by Django 6.0.1 on 2026-05-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0009_api_auto_test'),
        ('room', '0008_aiconversation_aimessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='related_tasks',
            field=models.ManyToManyField(blank=True, related_name='linked_api_test_cases', to='room.task', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='related_tasks',
            field=models.ManyToManyField(blank=True, related_name='linked_performance_test_cases', to='room.task', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='uitestcase',
            name='related_tasks',
            field=models.ManyToManyField(blank=True, related_name='linked_ui_test_cases', to='room.task', verbose_name='关联任务'),
        ),
        migrations.CreateModel(
            name='CiCdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('ci_type', models.CharField(choices=[('jenkins', 'Jenkins'), ('gitlab', 'GitLab CI'), ('github', 'GitHub Actions')], max_length=20, verbose_name='CI类型')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='API Token')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='监听分支')),
                ('auto_trigger', models.BooleanField(default=False, verbose_name='自动触发')),
                ('test_suite_ids', models.JSONField(default=list, verbose_name='关联测试套件')),
                ('headers', models.JSONField(default=dict, verbose_name='自定义请求头')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cicd_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicd_configs', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'CI/CD配置',
                'verbose_name_plural': 'CI/CD配置',
                'db_table': 'qa_cicd_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='状态')),
                ('commit_sha', models.CharField(blank=True, max_length=40, verbose_name='提交SHA')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='分支')),
                ('log_output', models.TextField(blank=True, verbose_name='执行日志')),
                ('test_results_summary', models.JSONField(default=dict, verbose_name='测试结果摘要')),
                ('started_at', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cicd_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='qa_center.cicdconfig', verbose_name='CI/CD配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Pipeline执行记录',
                'verbose_name_plural': 'Pipeline执行记录',
                'db_table': 'qa_pipeline_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
