# Generated by Django 6.0.1 on 2026-06-09 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0011_test_run_plan_and_case_timeout'),
        ('room', '0011_project_api_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('base_url', models.CharField(blank=True, max_length=500, verbose_name='Base URL')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='环境变量')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认环境')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_environments', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
                'db_table': 'qa_test_environments',
                'ordering': ['project', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='testrunplan',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_plans', to='qa_center.testenvironment', verbose_name='运行环境'),
        ),
        migrations.CreateModel(
            name='TestGlobalVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='变量名')),
                ('value', models.TextField(blank=True, verbose_name='变量值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感（前端脱敏）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_global_vars', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_global_vars', to='room.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试全局变量',
                'verbose_name_plural': '测试全局变量',
                'db_table': 'qa_test_global_vars',
                'ordering': ['project', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='testenvironment',
            index=models.Index(fields=['project', 'is_default'], name='qa_test_env_project_e67b63_idx'),
        ),
        migrations.AddConstraint(
            model_name='testenvironment',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_env_per_project_name'),
        ),
        migrations.AddConstraint(
            model_name='testglobalvar',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='uniq_global_var_per_project_key'),
        ),
    ]
