# Generated by Django 6.0.1 on 2026-06-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0012_add_test_environment_and_global_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAutoTestExtractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='变量名')),
                ('source', models.CharField(choices=[('body', '响应体 JSON'), ('header', '响应头'), ('status', '状态码'), ('cookie', 'Cookie'), ('response_time', '响应时间(ms)')], default='body', max_length=20, verbose_name='来源')),
                ('expression', models.CharField(blank=True, help_text='body: JSONPath; header/cookie: 名称; status/response_time: 留空', max_length=500, verbose_name='表达式')),
                ('default_value', models.CharField(blank=True, help_text='抽取失败时使用，避免后续 case 拿到 None', max_length=500, verbose_name='默认值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractors', to='qa_center.apiautotestcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': 'API自动化变量抽取器',
                'verbose_name_plural': 'API自动化变量抽取器',
                'db_table': 'qa_api_auto_extractors',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['case', 'is_active'], name='qa_api_auto_case_id_ccb96c_idx')],
            },
        ),
    ]
