# Generated by Django 6.0.1 on 2026-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0013_add_api_auto_test_extractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiautotestcase',
            name='enable_cookie_session',
            field=models.BooleanField(default=True, help_text='True：与同计划/套件内的其它用例共享 Session；False：每次新开连接', verbose_name='复用Session Cookie'),
        ),
        migrations.AddField(
            model_name='apiautotestcase',
            name='form_files',
            field=models.JSONField(blank=True, default=list, help_text='[{name, filename, content, content_type, encoding?}]', verbose_name='上传文件'),
        ),
        migrations.AddField(
            model_name='apiautotestcase',
            name='query_params',
            field=models.JSONField(blank=True, default=dict, help_text='{k: v} 或 [[k, v], ...] 支持重复键', verbose_name='Query参数'),
        ),
    ]
