# Generated by Django 6.0.1 on 2026-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0014_add_request_capability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='response_extractions',
            field=models.JSONField(blank=True, default=list, help_text='[{"json_path": "$.token", "var_name": "auth_token", "default": null}]', verbose_name='响应变量提取'),
        ),
    ]
