# Generated by Django 6.0.1 on 2026-06-11 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0015_apitestcase_response_extractions'),
        ('room', '0012_alter_taskactivitylog_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('manual', '手动'), ('scheduled', '定时'), ('cicd', 'CI/CD'), ('regression', '回归')], default='manual', max_length=20)),
                ('test_type', models.CharField(choices=[('api', 'API'), ('ui', 'UI'), ('performance', '性能'), ('mixed', '混合')], default='api', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '全部通过'), ('failed', '有失败'), ('error', '执行异常'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('total_count', models.IntegerField(default=0)),
                ('passed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_ms', models.IntegerField(null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('curl_template', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='room.project')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '测试运行',
                'verbose_name_plural': '测试运行',
                'db_table': 'qa_test_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('api', 'API'), ('ui', 'UI'), ('performance', '性能')], default='api', max_length=20)),
                ('sequence', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '异常'), ('skipped', '跳过')], default='pending', max_length=20)),
                ('duration_ms', models.IntegerField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('assertion_results', models.JSONField(blank=True, default=list)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('curl', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('legacy_api_result_id', models.IntegerField(null=True)),
                ('legacy_test_result_id', models.IntegerField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('api_test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_case_results', to='qa_center.apitestcase')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='qa_center.testrun')),
                ('ui_test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_case_results', to='qa_center.uitestcase')),
            ],
            options={
                'verbose_name': '测试运行用例结果',
                'verbose_name_plural': '测试运行用例结果',
                'db_table': 'qa_test_run_case_results',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['project', '-created_at'], name='qa_test_run_project_b9abde_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['status'], name='qa_test_run_status_683889_idx'),
        ),
        migrations.AddIndex(
            model_name='testruncaseresult',
            index=models.Index(fields=['test_run', 'status'], name='qa_test_run_test_ru_6189cc_idx'),
        ),
        migrations.AddIndex(
            model_name='testruncaseresult',
            index=models.Index(fields=['api_test_case', '-completed_at'], name='qa_test_run_api_tes_6621dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='testruncaseresult',
            constraint=models.UniqueConstraint(fields=('test_run', 'sequence'), name='uniq_test_run_sequence'),
        ),
    ]
