# Generated by Django 6.0.1 on 2026-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0016_testrun_testruncaseresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='aborted',
            field=models.BooleanField(default=False, verbose_name='是否被中止'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='错误码'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='error_traceback',
            field=models.TextField(blank=True, default='', verbose_name='错误堆栈'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='任务ID'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='temp_dir_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='临时目录'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='worker_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Worker PID'),
        ),
    ]
