# Generated by Django 6.0.1 on 2026-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_center", "0017_testresult_error_fields"),
        ("room", "0012_alter_taskactivitylog_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="cicdconfig",
            name="ci_url",
            field=models.URLField(blank=True, verbose_name="CI Server URL"),
        ),
        migrations.AddField(
            model_name="cicdconfig",
            name="ci_token",
            field=models.CharField(blank=True, max_length=255, verbose_name="CI API Token"),
        ),
        migrations.AddField(
            model_name="cicdconfig",
            name="ci_project",
            field=models.CharField(blank=True, max_length=255, verbose_name="CI Project/Repo"),
        ),
        migrations.AddField(
            model_name="cicdconfig",
            name="ci_job_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="CI Job/Pipeline Name"),
        ),
        migrations.AddField(
            model_name="cicdconfig",
            name="verify_ssl",
            field=models.BooleanField(default=True, verbose_name="Verify SSL"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="ci_type",
            field=models.CharField(blank=True, max_length=20, verbose_name="CI类型"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="external_queue_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="外部队列ID"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="external_run_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="外部运行ID"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="外部URL"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="错误信息"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="is_mock",
            field=models.BooleanField(default=True, verbose_name="是否为模拟数据"),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="jobs_summary",
            field=models.JSONField(blank=True, default=list, verbose_name="Job摘要"),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_run_id__gt", "")),
                fields=("cicd_config", "external_run_id"),
                name="uniq_cicd_external_run",
            ),
        ),
    ]
