# Generated by Django 6.0.1 on 2026-07-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0024_testresult_api_auto_result_fk'),
        ('room', '0012_alter_taskactivitylog_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinerun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pipeline????', 'verbose_name_plural': 'Pipeline????'},
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Trace ID'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='ci_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='CI??'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='cicd_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='qa_center.cicdconfig', verbose_name='CI/CD??'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='commit_sha',
            field=models.CharField(blank=True, max_length=40, verbose_name='??SHA'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='external_queue_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='????ID'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='external_run_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='????ID'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='??URL'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='is_mock',
            field=models.BooleanField(default=True, verbose_name='???????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='jobs_summary',
            field=models.JSONField(blank=True, default=list, verbose_name='Job??'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='log_output',
            field=models.TextField(blank=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='room.project', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='test_results_summary',
            field=models.JSONField(default=dict, verbose_name='??????'),
        ),
    ]
