# Generated by Django 6.0.1 on 2026-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0025_pipeline_run_trace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='lifecycle_reason',
            field=models.CharField(blank=True, default='', help_text='如 probe_failed / locust_start_failed / user_stopped', max_length=256, verbose_name='生命周期状态原因'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='lifecycle_state',
            field=models.CharField(choices=[('pending', '等待执行'), ('preparing', '准备中'), ('probing', '连通性检查'), ('starting', '启动中'), ('ramping', '加压中'), ('running', '运行中'), ('collecting', '收集中'), ('stopping', '正在停止'), ('passed', '通过'), ('failed', '未通过'), ('error', '异常'), ('stopped', '已停止'), ('timeout', '超时')], db_index=True, default='pending', max_length=20, verbose_name='生命周期状态'),
        ),
    ]
