# Generated by Django 6.0.1 on 2026-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0026_add_lifecycle_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancetestcase',
            name='assertions',
            field=models.JSONField(blank=True, default=list, help_text='[{"type":"status_code","op":"in","expect":[200,201]},{"type":"p95","op":"lt","expect":500}]', verbose_name='断言配置'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"type":"bearer","token":"{{ENV_TOKEN}}"} / {"type":"basic","username":"","password":""}', verbose_name='认证配置'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='body_type',
            field=models.CharField(choices=[('none', '无'), ('json', 'JSON'), ('form', '表单'), ('raw', '原始文本')], default='json', max_length=10, verbose_name='请求体类型'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='follow_redirects',
            field=models.BooleanField(default=True, verbose_name='跟随重定向'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='query_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Query参数'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='request_timeout',
            field=models.IntegerField(default=30, verbose_name='请求超时(秒)'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='[{"name":"login","url":"/login","method":"POST","body":{...},"extract":{"token":"$.token"}},...]', verbose_name='多步骤场景'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='think_time_max',
            field=models.FloatField(default=0.5, verbose_name='思考时间最大值(秒)'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='think_time_min',
            field=models.FloatField(default=0.1, verbose_name='思考时间最小值(秒)'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='verify_ssl',
            field=models.BooleanField(default=True, verbose_name='验证SSL证书'),
        ),
        migrations.AddField(
            model_name='performancetestcase',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='权重'),
        ),
        migrations.AddField(
            model_name='performancetestresult',
            name='assertion_results',
            field=models.JSONField(blank=True, default=list, verbose_name='断言结果'),
        ),
        migrations.AddField(
            model_name='performancetestresult',
            name='step_results',
            field=models.JSONField(blank=True, default=list, verbose_name='步骤级结果'),
        ),
    ]
