# Generated by Django for TestTask webhook token

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0028_uitestcase_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='webhook_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='外部系统触发本任务时的凭证（无会话认证端点使用）', unique=True, verbose_name='Webhook 触发令牌'),
        ),
    ]
