# Generated by Django 6.0.1 on 2026-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_center', '0029_testtask_webhook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误'), ('running', '运行中'), ('pending', '待执行'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='测试状态'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='idle', max_length=20, verbose_name='当前状态'),
        ),
    ]
