# Generated by Django migration manager on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_notification'),
    ]

    operations = [
        # 为 Task 模型添加索引
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column'], name='task_column_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['position'], name='task_position_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='task_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column', 'position'], name='task_column_pos_idx'),
        ),

        # 为 Column 模型添加索引
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['project'], name='column_project_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['project', 'position'], name='column_project_pos_idx'),
        ),

        # 为 Project 成员关系添加索引（用于成员查询）
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='project_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_created_idx'),
        ),

        # 为 Tag 模型添加索引
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['project'], name='tag_project_idx'),
        ),

        # 为 Notification 模型添加索引
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notif_user_created_idx'),
        ),
    ]