# Generated by Django 6.0.1 on 2026-05-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_aiconversation_aimessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task', '任务'), ('member', '成员'), ('system', '系统'), ('success', '成功'), ('warning', '警告'), ('test_failure', '测试失败'), ('deploy_success', '部署成功'), ('quality_risk', '质量风险')], default='system', max_length=30),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='room.project')),
            ],
            options={
                'db_table': 'sprint',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='room.sprint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='room.task')),
            ],
            options={
                'db_table': 'sprint_task',
                'unique_together': {('sprint', 'task')},
            },
        ),
    ]
