# Generated by Django 6.0.1 on 2026-05-09 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_task_activity_log_user_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApiDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('format', models.CharField(choices=[('markdown', 'Markdown'), ('openapi_json', 'OpenAPI JSON'), ('text', '纯文本')], default='markdown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_docs', to='room.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_api_doc',
                'ordering': ['-created_at'],
            },
        ),
    ]
