# Generated by Django 6.0.1 on 2026-06-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_project_api_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='room.task'),
        ),
    ]
